#! /bin/sh

BLUE="#42A5F5"
RED="#EC7875"
YELLOW="#FDD835"
GREEN="#61C766"
MAGENTA="#BA68C8"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color = "#42A5F5"
bspc config active_border_color = "#BA68C8"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Viewnior state=floating focus=on

bash ~/.config/polybar/custom/launch.sh

ksuperkey &
feh --bg-center ~/wallpapers/wal3.png
